### ISSUE TITLE
我有两个问题

### ISSUE THREAD

**Issue by beifen886** [jones2000/hqchartPy2#5]
1.免费版完全支持通达信吗？
2.有更高级的版本吗？多少钱？

**Comment by jones2000** [comment]
免费版支持大部分通达信函数。我没有通达信的源码， 所有的函数算法，都是在网站找的，如果网上找不到的算法的函数，就没有。

付费版本，都是定制版本，可以帮客户定制一些函数。具体看需求，然后评估工时和费用。

**Comment by beifen886** [comment]
> 免费版支持大部分通达信函数。我没有通达信的源码， 所有的函数算法，都是在网站找的，如果网上找不到的算法的函数，就没有。
> 
> 付费版本，都是定制版本，可以帮客户定制一些函数。具体看需求，然后评估工时和费用。

好的 👍
